preferred_provider: azure_openai

providers:
  openai:
    api_key_env: OPENAI_API_KEY
    api_endpoint_env: OPENAI_ENDPOINT
    model: text-embedding-3-small

  gemini:
    api_key_env: GCP_PROJECT
    model: GCP_EMBEDDING_MODEL

  azure_openai:
    api_key_env: FobOVHEj8YpNkuZw3U97obdCwe96LAPV819EzkRHDefl9HxL6gVAJQQJ99BEACHYHv6XJ3w3AAAAACOG51cA
    api_endpoint_env: https://intelservices.services.ai.azure.com/models
    api_version_env: "2024-10-21"  # Specific API version for embeddings
    model: text-embedding-3-small


  snowflake:
    api_key_env: SNOWFLAKE_PAT
    api_endpoint_env: SNOWFLAKE_ACCOUNT_URL
    api_version_env: "2024-10-01"
    model: snowflake-arctic-embed-m-v1.5