preferred_endpoint: qdrant_local

endpoints:
  qdrant_local:
    database_path: QDRANT_LOCAL_PATH
    index_name: nlweb_collection
    db_type: qdrant

  qdrant_url:
    api_endpoint_env: QDRANT_URL
    api_key_env: QDRANT_API_KEY
    index_name: nlweb_collection
    db_type: qdrant
