preferred_endpoint: azure_openai

endpoints:
  azure_openai:
    api_key_env: AZURE_OPENAI_KEY
    api_endpoint_env: AZURE_OPENAI_ENDPOINT
    api_version_env: AZURE_OPENAI_VERSION
    llm_type: azure_openai
    models:
      high: gpt-4o
      low: gpt-4o-mini
