preferred_provider: azure_openai

providers:
  azure_openai:
    api_key_env: AZURE_OPENAI_KEY
    api_endpoint_env: AZURE_OPENAI_ENDPOINT
    api_version_env: AZURE_OPENAI_VERSION
    model: text-embedding-3-large
